/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 52
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_blank_line = 1,
  sym__newline = 2,
  anon_sym_POUND_POUND_POUND_POUND_POUND_POUND = 3,
  aux_sym_heading6_token1 = 4,
  anon_sym_LF = 5,
  anon_sym_POUND_POUND_POUND_POUND_POUND = 6,
  anon_sym_POUND_POUND_POUND_POUND = 7,
  anon_sym_POUND_POUND_POUND = 8,
  anon_sym_POUND_POUND = 9,
  anon_sym_POUND = 10,
  anon_sym_DASH_POUND = 11,
  anon_sym_BQUOTE = 12,
  aux_sym_code_span_token1 = 13,
  anon_sym_STAR_STAR = 14,
  sym__bold_content = 15,
  anon_sym_STAR = 16,
  sym__italic_content = 17,
  anon_sym___ = 18,
  sym__underline_content = 19,
  anon_sym_TILDE_TILDE = 20,
  sym__strikethrough_content = 21,
  sym_link = 22,
  sym_text = 23,
  sym_document = 24,
  sym__block = 25,
  sym_heading6 = 26,
  sym_heading5 = 27,
  sym_heading4 = 28,
  sym_heading3 = 29,
  sym_heading2 = 30,
  sym_heading1 = 31,
  sym_subheading = 32,
  sym_paragraph = 33,
  sym__inline_content = 34,
  sym__inline = 35,
  sym_code_span = 36,
  sym_bold = 37,
  sym_italic = 38,
  sym_underline = 39,
  sym_strikethrough = 40,
  aux_sym_document_repeat1 = 41,
  aux_sym__inline_content_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_blank_line] = "blank_line",
  [sym__newline] = "_newline",
  [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = "######",
  [aux_sym_heading6_token1] = "heading6_token1",
  [anon_sym_LF] = "\n",
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = "#####",
  [anon_sym_POUND_POUND_POUND_POUND] = "####",
  [anon_sym_POUND_POUND_POUND] = "###",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_POUND] = "#",
  [anon_sym_DASH_POUND] = "-#",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_code_span_token1] = "code_content",
  [anon_sym_STAR_STAR] = "**",
  [sym__bold_content] = "content",
  [anon_sym_STAR] = "*",
  [sym__italic_content] = "content",
  [anon_sym___] = "__",
  [sym__underline_content] = "content",
  [anon_sym_TILDE_TILDE] = "~~",
  [sym__strikethrough_content] = "content",
  [sym_link] = "link",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_heading6] = "heading6",
  [sym_heading5] = "heading5",
  [sym_heading4] = "heading4",
  [sym_heading3] = "heading3",
  [sym_heading2] = "heading2",
  [sym_heading1] = "heading1",
  [sym_subheading] = "subheading",
  [sym_paragraph] = "paragraph",
  [sym__inline_content] = "_inline_content",
  [sym__inline] = "_inline",
  [sym_code_span] = "code_span",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_underline] = "underline",
  [sym_strikethrough] = "strikethrough",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym__inline_content_repeat1] = "_inline_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_blank_line] = sym_blank_line,
  [sym__newline] = sym__newline,
  [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
  [aux_sym_heading6_token1] = aux_sym_heading6_token1,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND_POUND,
  [anon_sym_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DASH_POUND] = anon_sym_DASH_POUND,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_code_span_token1] = aux_sym_code_span_token1,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [sym__bold_content] = sym__bold_content,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym__italic_content] = sym__bold_content,
  [anon_sym___] = anon_sym___,
  [sym__underline_content] = sym__bold_content,
  [anon_sym_TILDE_TILDE] = anon_sym_TILDE_TILDE,
  [sym__strikethrough_content] = sym__bold_content,
  [sym_link] = sym_link,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_heading6] = sym_heading6,
  [sym_heading5] = sym_heading5,
  [sym_heading4] = sym_heading4,
  [sym_heading3] = sym_heading3,
  [sym_heading2] = sym_heading2,
  [sym_heading1] = sym_heading1,
  [sym_subheading] = sym_subheading,
  [sym_paragraph] = sym_paragraph,
  [sym__inline_content] = sym__inline_content,
  [sym__inline] = sym__inline,
  [sym_code_span] = sym_code_span,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_underline] = sym_underline,
  [sym_strikethrough] = sym_strikethrough,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym__inline_content_repeat1] = aux_sym__inline_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_heading6_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_span_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym__bold_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym__italic_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [sym__underline_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TILDE_TILDE] = {
    .visible = true,
    .named = false,
  },
  [sym__strikethrough_content] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_heading6] = {
    .visible = true,
    .named = true,
  },
  [sym_heading5] = {
    .visible = true,
    .named = true,
  },
  [sym_heading4] = {
    .visible = true,
    .named = true,
  },
  [sym_heading3] = {
    .visible = true,
    .named = true,
  },
  [sym_heading2] = {
    .visible = true,
    .named = true,
  },
  [sym_heading1] = {
    .visible = true,
    .named = true,
  },
  [sym_subheading] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_content] = {
    .visible = false,
    .named = true,
  },
  [sym__inline] = {
    .visible = false,
    .named = true,
  },
  [sym_code_span] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_underline] = {
    .visible = true,
    .named = true,
  },
  [sym_strikethrough] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inline_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 21,
        '#', 38,
        '*', 32,
        '-', 33,
        '[', 43,
        '_', 39,
        '`', 43,
        '~', 40,
        '\t', 41,
        ' ', 41,
      );
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(50);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '[') ADVANCE(55);
      if (lookahead == '_') ADVANCE(52);
      if (lookahead == '`') ADVANCE(28);
      if (lookahead == '~') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(49);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '_') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == '~') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '_') ADVANCE(45);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '~') ADVANCE(47);
      END_STATE();
    case 14:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 21,
        '#', 26,
        '*', 32,
        '-', 51,
        '[', 55,
        '_', 52,
        '`', 28,
        '~', 53,
      );
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 18,
        '#', 26,
        '*', 32,
        '-', 51,
        '[', 55,
        '_', 52,
        '`', 28,
        '~', 53,
      );
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND_POUND_POUND);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_heading6_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(19);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      if (lookahead == '#') ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH_POUND);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__bold_content);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(30);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '[' ||
          lookahead == '_' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(42);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '#') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '_') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '~') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead == '#' ||
          lookahead == '[' ||
          lookahead == '_' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead == '#' ||
          lookahead == '[' ||
          lookahead == '_' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__italic_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__underline_content);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_TILDE_TILDE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__strikethrough_content);
      if (lookahead == '~') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_link);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_link);
      if (lookahead == ')') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != '_' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '_') ADVANCE(44);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '~') ADVANCE(46);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != '_' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 15},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [aux_sym_heading6_token1] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DASH_POUND] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym__italic_content] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_TILDE_TILDE] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(45),
    [sym__block] = STATE(2),
    [sym_heading6] = STATE(2),
    [sym_heading5] = STATE(2),
    [sym_heading4] = STATE(2),
    [sym_heading3] = STATE(2),
    [sym_heading2] = STATE(2),
    [sym_heading1] = STATE(2),
    [sym_subheading] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym__inline_content] = STATE(8),
    [sym__inline] = STATE(4),
    [sym_code_span] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_underline] = STATE(4),
    [sym_strikethrough] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym__inline_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_blank_line] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = ACTIONS(9),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(11),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(13),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(15),
    [anon_sym_POUND_POUND] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(19),
    [anon_sym_DASH_POUND] = ACTIONS(21),
    [anon_sym_BQUOTE] = ACTIONS(23),
    [anon_sym_STAR_STAR] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym___] = ACTIONS(29),
    [anon_sym_TILDE_TILDE] = ACTIONS(31),
    [sym_link] = ACTIONS(33),
    [sym_text] = ACTIONS(35),
  },
  [STATE(2)] = {
    [sym__block] = STATE(3),
    [sym_heading6] = STATE(3),
    [sym_heading5] = STATE(3),
    [sym_heading4] = STATE(3),
    [sym_heading3] = STATE(3),
    [sym_heading2] = STATE(3),
    [sym_heading1] = STATE(3),
    [sym_subheading] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym__inline_content] = STATE(8),
    [sym__inline] = STATE(4),
    [sym_code_span] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_underline] = STATE(4),
    [sym_strikethrough] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym__inline_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_blank_line] = ACTIONS(39),
    [sym__newline] = ACTIONS(41),
    [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = ACTIONS(9),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(11),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(13),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(15),
    [anon_sym_POUND_POUND] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(19),
    [anon_sym_DASH_POUND] = ACTIONS(21),
    [anon_sym_BQUOTE] = ACTIONS(23),
    [anon_sym_STAR_STAR] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym___] = ACTIONS(29),
    [anon_sym_TILDE_TILDE] = ACTIONS(31),
    [sym_link] = ACTIONS(33),
    [sym_text] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym__block] = STATE(3),
    [sym_heading6] = STATE(3),
    [sym_heading5] = STATE(3),
    [sym_heading4] = STATE(3),
    [sym_heading3] = STATE(3),
    [sym_heading2] = STATE(3),
    [sym_heading1] = STATE(3),
    [sym_subheading] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym__inline_content] = STATE(8),
    [sym__inline] = STATE(4),
    [sym_code_span] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_underline] = STATE(4),
    [sym_strikethrough] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym__inline_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_blank_line] = ACTIONS(45),
    [sym__newline] = ACTIONS(48),
    [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = ACTIONS(51),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(54),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(57),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(60),
    [anon_sym_POUND_POUND] = ACTIONS(63),
    [anon_sym_POUND] = ACTIONS(66),
    [anon_sym_DASH_POUND] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(72),
    [anon_sym_STAR_STAR] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(78),
    [anon_sym___] = ACTIONS(81),
    [anon_sym_TILDE_TILDE] = ACTIONS(84),
    [sym_link] = ACTIONS(87),
    [sym_text] = ACTIONS(90),
  },
  [STATE(4)] = {
    [sym__inline] = STATE(5),
    [sym_code_span] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_underline] = STATE(5),
    [sym_strikethrough] = STATE(5),
    [aux_sym__inline_content_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym_blank_line] = ACTIONS(93),
    [sym__newline] = ACTIONS(95),
    [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = ACTIONS(93),
    [anon_sym_LF] = ACTIONS(95),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(95),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(95),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(95),
    [anon_sym_POUND_POUND] = ACTIONS(95),
    [anon_sym_POUND] = ACTIONS(95),
    [anon_sym_DASH_POUND] = ACTIONS(93),
    [anon_sym_BQUOTE] = ACTIONS(23),
    [anon_sym_STAR_STAR] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym___] = ACTIONS(29),
    [anon_sym_TILDE_TILDE] = ACTIONS(31),
    [sym_link] = ACTIONS(97),
    [sym_text] = ACTIONS(99),
  },
  [STATE(5)] = {
    [sym__inline] = STATE(5),
    [sym_code_span] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_underline] = STATE(5),
    [sym_strikethrough] = STATE(5),
    [aux_sym__inline_content_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym_blank_line] = ACTIONS(101),
    [sym__newline] = ACTIONS(103),
    [anon_sym_POUND_POUND_POUND_POUND_POUND_POUND] = ACTIONS(101),
    [anon_sym_LF] = ACTIONS(103),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(103),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(103),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(103),
    [anon_sym_POUND_POUND] = ACTIONS(103),
    [anon_sym_POUND] = ACTIONS(103),
    [anon_sym_DASH_POUND] = ACTIONS(101),
    [anon_sym_BQUOTE] = ACTIONS(105),
    [anon_sym_STAR_STAR] = ACTIONS(108),
    [anon_sym_STAR] = ACTIONS(111),
    [anon_sym___] = ACTIONS(114),
    [anon_sym_TILDE_TILDE] = ACTIONS(117),
    [sym_link] = ACTIONS(120),
    [sym_text] = ACTIONS(123),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(126), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
    ACTIONS(128), 9,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
  [23] = 3,
    ACTIONS(134), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(130), 8,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      sym_link,
    ACTIONS(132), 9,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
  [48] = 3,
    ACTIONS(140), 1,
      anon_sym_LF,
    ACTIONS(138), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(136), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [73] = 3,
    ACTIONS(146), 1,
      anon_sym_STAR_STAR,
    ACTIONS(142), 8,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
    ACTIONS(144), 9,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
  [98] = 3,
    ACTIONS(152), 1,
      anon_sym_STAR,
    ACTIONS(150), 8,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      sym_text,
    ACTIONS(148), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [123] = 3,
    ACTIONS(158), 1,
      anon_sym___,
    ACTIONS(154), 8,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym_TILDE_TILDE,
      sym_link,
    ACTIONS(156), 9,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
  [148] = 3,
    ACTIONS(164), 1,
      anon_sym_LF,
    ACTIONS(162), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(160), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [173] = 3,
    ACTIONS(170), 1,
      anon_sym_LF,
    ACTIONS(168), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(166), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [198] = 3,
    ACTIONS(176), 1,
      anon_sym_LF,
    ACTIONS(174), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(172), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [223] = 3,
    ACTIONS(182), 1,
      anon_sym_LF,
    ACTIONS(180), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(178), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [248] = 3,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(186), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(184), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [273] = 3,
    ACTIONS(194), 1,
      anon_sym_LF,
    ACTIONS(192), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(190), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [298] = 3,
    ACTIONS(200), 1,
      anon_sym_LF,
    ACTIONS(198), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(196), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [323] = 2,
    ACTIONS(202), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
    ACTIONS(204), 9,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
  [346] = 2,
    ACTIONS(206), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
    ACTIONS(208), 9,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
  [369] = 2,
    ACTIONS(210), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
    ACTIONS(212), 9,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
  [392] = 2,
    ACTIONS(214), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
    ACTIONS(216), 9,
      sym__newline,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
  [415] = 2,
    ACTIONS(220), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(218), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [437] = 2,
    ACTIONS(224), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(222), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [459] = 2,
    ACTIONS(228), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(226), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [481] = 2,
    ACTIONS(232), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(230), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [503] = 2,
    ACTIONS(236), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(234), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [525] = 2,
    ACTIONS(240), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(238), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [547] = 2,
    ACTIONS(244), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(242), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [569] = 2,
    ACTIONS(248), 8,
      sym__newline,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND,
      anon_sym_STAR,
      sym_text,
    ACTIONS(246), 9,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_POUND_POUND_POUND_POUND_POUND,
      anon_sym_DASH_POUND,
      anon_sym_BQUOTE,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_TILDE_TILDE,
      sym_link,
  [591] = 9,
    ACTIONS(23), 1,
      anon_sym_BQUOTE,
    ACTIONS(25), 1,
      anon_sym_STAR_STAR,
    ACTIONS(27), 1,
      anon_sym_STAR,
    ACTIONS(29), 1,
      anon_sym___,
    ACTIONS(31), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(33), 1,
      sym_link,
    ACTIONS(35), 1,
      sym_text,
    STATE(16), 1,
      sym__inline_content,
    STATE(4), 7,
      sym__inline,
      sym_code_span,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      aux_sym__inline_content_repeat1,
  [625] = 9,
    ACTIONS(23), 1,
      anon_sym_BQUOTE,
    ACTIONS(25), 1,
      anon_sym_STAR_STAR,
    ACTIONS(27), 1,
      anon_sym_STAR,
    ACTIONS(29), 1,
      anon_sym___,
    ACTIONS(31), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(33), 1,
      sym_link,
    ACTIONS(35), 1,
      sym_text,
    STATE(14), 1,
      sym__inline_content,
    STATE(4), 7,
      sym__inline,
      sym_code_span,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      aux_sym__inline_content_repeat1,
  [659] = 9,
    ACTIONS(23), 1,
      anon_sym_BQUOTE,
    ACTIONS(25), 1,
      anon_sym_STAR_STAR,
    ACTIONS(27), 1,
      anon_sym_STAR,
    ACTIONS(29), 1,
      anon_sym___,
    ACTIONS(31), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(33), 1,
      sym_link,
    ACTIONS(35), 1,
      sym_text,
    STATE(13), 1,
      sym__inline_content,
    STATE(4), 7,
      sym__inline,
      sym_code_span,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      aux_sym__inline_content_repeat1,
  [693] = 9,
    ACTIONS(23), 1,
      anon_sym_BQUOTE,
    ACTIONS(25), 1,
      anon_sym_STAR_STAR,
    ACTIONS(27), 1,
      anon_sym_STAR,
    ACTIONS(29), 1,
      anon_sym___,
    ACTIONS(31), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(33), 1,
      sym_link,
    ACTIONS(35), 1,
      sym_text,
    STATE(12), 1,
      sym__inline_content,
    STATE(4), 7,
      sym__inline,
      sym_code_span,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      aux_sym__inline_content_repeat1,
  [727] = 9,
    ACTIONS(23), 1,
      anon_sym_BQUOTE,
    ACTIONS(25), 1,
      anon_sym_STAR_STAR,
    ACTIONS(27), 1,
      anon_sym_STAR,
    ACTIONS(29), 1,
      anon_sym___,
    ACTIONS(31), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(33), 1,
      sym_link,
    ACTIONS(35), 1,
      sym_text,
    STATE(18), 1,
      sym__inline_content,
    STATE(4), 7,
      sym__inline,
      sym_code_span,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      aux_sym__inline_content_repeat1,
  [761] = 9,
    ACTIONS(23), 1,
      anon_sym_BQUOTE,
    ACTIONS(25), 1,
      anon_sym_STAR_STAR,
    ACTIONS(27), 1,
      anon_sym_STAR,
    ACTIONS(29), 1,
      anon_sym___,
    ACTIONS(31), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(33), 1,
      sym_link,
    ACTIONS(35), 1,
      sym_text,
    STATE(17), 1,
      sym__inline_content,
    STATE(4), 7,
      sym__inline,
      sym_code_span,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      aux_sym__inline_content_repeat1,
  [795] = 9,
    ACTIONS(23), 1,
      anon_sym_BQUOTE,
    ACTIONS(25), 1,
      anon_sym_STAR_STAR,
    ACTIONS(27), 1,
      anon_sym_STAR,
    ACTIONS(29), 1,
      anon_sym___,
    ACTIONS(31), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(33), 1,
      sym_link,
    ACTIONS(35), 1,
      sym_text,
    STATE(15), 1,
      sym__inline_content,
    STATE(4), 7,
      sym__inline,
      sym_code_span,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      aux_sym__inline_content_repeat1,
  [829] = 1,
    ACTIONS(250), 1,
      aux_sym_heading6_token1,
  [833] = 1,
    ACTIONS(252), 1,
      aux_sym_heading6_token1,
  [837] = 1,
    ACTIONS(254), 1,
      sym__underline_content,
  [841] = 1,
    ACTIONS(256), 1,
      sym__strikethrough_content,
  [845] = 1,
    ACTIONS(258), 1,
      aux_sym_heading6_token1,
  [849] = 1,
    ACTIONS(260), 1,
      aux_sym_heading6_token1,
  [853] = 1,
    ACTIONS(262), 1,
      aux_sym_heading6_token1,
  [857] = 1,
    ACTIONS(264), 1,
      ts_builtin_sym_end,
  [861] = 1,
    ACTIONS(266), 1,
      aux_sym_code_span_token1,
  [865] = 1,
    ACTIONS(268), 1,
      aux_sym_heading6_token1,
  [869] = 1,
    ACTIONS(270), 1,
      anon_sym_BQUOTE,
  [873] = 1,
    ACTIONS(272), 1,
      aux_sym_heading6_token1,
  [877] = 1,
    ACTIONS(274), 1,
      sym__bold_content,
  [881] = 1,
    ACTIONS(276), 1,
      sym__italic_content,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 23,
  [SMALL_STATE(8)] = 48,
  [SMALL_STATE(9)] = 73,
  [SMALL_STATE(10)] = 98,
  [SMALL_STATE(11)] = 123,
  [SMALL_STATE(12)] = 148,
  [SMALL_STATE(13)] = 173,
  [SMALL_STATE(14)] = 198,
  [SMALL_STATE(15)] = 223,
  [SMALL_STATE(16)] = 248,
  [SMALL_STATE(17)] = 273,
  [SMALL_STATE(18)] = 298,
  [SMALL_STATE(19)] = 323,
  [SMALL_STATE(20)] = 346,
  [SMALL_STATE(21)] = 369,
  [SMALL_STATE(22)] = 392,
  [SMALL_STATE(23)] = 415,
  [SMALL_STATE(24)] = 437,
  [SMALL_STATE(25)] = 459,
  [SMALL_STATE(26)] = 481,
  [SMALL_STATE(27)] = 503,
  [SMALL_STATE(28)] = 525,
  [SMALL_STATE(29)] = 547,
  [SMALL_STATE(30)] = 569,
  [SMALL_STATE(31)] = 591,
  [SMALL_STATE(32)] = 625,
  [SMALL_STATE(33)] = 659,
  [SMALL_STATE(34)] = 693,
  [SMALL_STATE(35)] = 727,
  [SMALL_STATE(36)] = 761,
  [SMALL_STATE(37)] = 795,
  [SMALL_STATE(38)] = 829,
  [SMALL_STATE(39)] = 833,
  [SMALL_STATE(40)] = 837,
  [SMALL_STATE(41)] = 841,
  [SMALL_STATE(42)] = 845,
  [SMALL_STATE(43)] = 849,
  [SMALL_STATE(44)] = 853,
  [SMALL_STATE(45)] = 857,
  [SMALL_STATE(46)] = 861,
  [SMALL_STATE(47)] = 865,
  [SMALL_STATE(48)] = 869,
  [SMALL_STATE(49)] = 873,
  [SMALL_STATE(50)] = 877,
  [SMALL_STATE(51)] = 881,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_content, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__inline_content, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strikethrough, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strikethrough, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underline, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_underline, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading6, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading6, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading5, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading5, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading4, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading4, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading3, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading3, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading2, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading2, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading1, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading1, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subheading, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subheading, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underline, 3, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_underline, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strikethrough, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strikethrough, 3, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subheading, 4, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subheading, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading6, 4, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading6, 4, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading5, 4, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading5, 4, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading4, 4, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading4, 4, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading3, 4, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading3, 4, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading2, 4, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading2, 4, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading1, 4, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading1, 4, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [264] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_astrum_md(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
